name: slinkshot_clone
description: Slink Shot App clone by Mohammed Bakr .


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  provider: ^4.3.2+2
  http: ^0.12.2
  connectivity: ^2.0.2
  url_launcher: ^5.7.10
  youtube_player_flutter: ^7.0.0+7
  shared_preferences: ^0.5.12+4
  carousel_slider: ^3.0.0
  flutter_spinning_wheel: ^1.1.0
#  webview_flutter: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter



# The following section is specific to Flutter.
flutter:


  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/spin/

